/*
 * Copyright (c) 2019 Murilo Ijanc' <mbsd@m0x.ru>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#define D_HEADER \
	"<html>\n" \
	"<head>\n" \
        "<meta charset=\"utf-8\">\n" \
	"\t\t<title>ana static site generator</title>\n" \
	"</head>\n" \
	"<body>\n"
#define D_FOOTER \
        "\t<hr>\n" \
        "\t<p style=\"text-align:center;\">generated by" \
        " <a href=\"https://ana.m0x.ru\"><b>ana</b></a>" \
        " at 20/09/2019 10:52 AM</p>\n" \
        "</body>\n" \
        "</html>"
#define D_HEADER_F 	"%s/_header.html"	/* arquivo header */
#define D_FOOTER_F 	"%s/_footer.html"	/* arquivo footer */
#define D_CACHE_F	"%s/.files"		/* arquivo de cache */
#define D_IGNORE_F	"%s/.anaignore"		/* arquivo exclusão */


struct lines {
	char *line;
	struct lines *next;
};
